// ABOUTME: Regression tests for the generate-image CLI.
// ABOUTME: Each test runs the compiled binary as a subprocess, matching the real user entry point.

package regression

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"testing"
)

var (
	binaryPath string
	buildOnce  sync.Once
	buildErr   error
)

// buildBinary compiles the CLI binary once for all tests.
func buildBinary(t *testing.T) string {
	t.Helper()
	buildOnce.Do(func() {
		tmpDir := os.TempDir()
		binaryPath = filepath.Join(tmpDir, "generate-image-test")
		cmd := exec.Command("go", "build", "-o", binaryPath, ".")
		cmd.Dir = filepath.Join(projectRoot())
		out, err := cmd.CombinedOutput()
		if err != nil {
			buildErr = fmt.Errorf("build failed: %s\n%s", err, out)
		}
	})
	if buildErr != nil {
		t.Fatalf("Failed to build binary: %v", buildErr)
	}
	return binaryPath
}

// projectRoot returns the root of the project (two levels up from this test file).
func projectRoot() string {
	// tests/regression/ -> project root
	dir, _ := os.Getwd()
	return filepath.Join(dir, "..", "..")
}

// setupEnv creates a temp directory with .env and config.yaml next to a copy
// of the binary, so the binary resolves config from its own directory.
// Thin wrapper around setupEnvWithConfig for the common case.
func setupEnv(t *testing.T, binary string, falKey string, configYAML string) string {
	t.Helper()
	dotEnv := ""
	if falKey != "" {
		dotEnv = fmt.Sprintf("FAL_KEY=%s\n", falKey)
	}
	return setupEnvWithConfig(t, binary, dotEnv, configYAML)
}

// runBinary executes the binary with the given args, stdin, and env vars.
// Returns stdout, stderr, and the exit code.
func runBinary(t *testing.T, binPath string, args []string, stdin string, env []string) (string, string, int) {
	t.Helper()
	cmd := exec.Command(binPath, args...)
	if stdin != "" {
		cmd.Stdin = strings.NewReader(stdin)
	} else {
		// Explicitly provide empty stdin (closed pipe, not terminal)
		cmd.Stdin = strings.NewReader("")
	}
	var stdout, stderr strings.Builder
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	cmd.Env = append(os.Environ(), env...)

	err := cmd.Run()
	exitCode := 0
	if exitErr, ok := err.(*exec.ExitError); ok {
		exitCode = exitErr.ExitCode()
	} else if err != nil {
		t.Fatalf("Failed to run binary: %v", err)
	}

	return stdout.String(), stderr.String(), exitCode
}

// startFakeAPI starts a test HTTP server that mimics the FAL API.
// generateHandler handles the image generation endpoint.
// pricingHandler handles the pricing endpoint (nil = 404).
// Returns the server and its URL.
func startFakeAPI(t *testing.T, generateHandler http.HandlerFunc, pricingHandler http.HandlerFunc) *httptest.Server {
	t.Helper()
	mux := http.NewServeMux()
	// Catch-all for generation endpoints (any model path)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		if strings.HasPrefix(r.URL.Path, "/v1/models/pricing") {
			if pricingHandler != nil {
				pricingHandler(w, r)
			} else {
				http.NotFound(w, r)
			}
			return
		}
		if generateHandler != nil {
			generateHandler(w, r)
		} else {
			http.NotFound(w, r)
		}
	})
	server := httptest.NewServer(mux)
	t.Cleanup(server.Close)
	return server
}

// fakeImagePNG is a valid 1x1 red PNG generated by ImageMagick.
var fakeImagePNG = []byte{
	0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d,
	0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
	0x01, 0x03, 0x00, 0x00, 0x00, 0x25, 0xdb, 0x56, 0xca, 0x00, 0x00, 0x00,
	0x06, 0x50, 0x4c, 0x54, 0x45, 0xff, 0x00, 0x00, 0xff, 0xff, 0xff, 0x41,
	0x1d, 0x34, 0x11, 0x00, 0x00, 0x00, 0x0a, 0x49, 0x44, 0x41, 0x54, 0x08,
	0xd7, 0x63, 0x60, 0x00, 0x00, 0x00, 0x02, 0x00, 0x01, 0xe2, 0x21, 0xbc,
	0x33, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4e, 0x44, 0xae, 0x42, 0x60,
	0x82,
}

// fakeImageJPEG is a minimal valid JPEG (1x1 pixel).
var fakeImageJPEG = []byte{
	0xff, 0xd8, 0xff, 0xe0, 0x00, 0x10, 0x4a, 0x46, 0x49, 0x46, 0x00, 0x01,
	0x01, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0xff, 0xd9,
}

// newImageServer creates an httptest server that serves fake image bytes with the given content type.
func newImageServer(t *testing.T, imageBytes []byte, contentType string) *httptest.Server {
	t.Helper()
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", contentType)
		w.Write(imageBytes)
	}))
	t.Cleanup(server.Close)
	return server
}

// successHandler returns a handler that serves a fake image and records the request.
func successHandler(t *testing.T, imageServer *httptest.Server, capturedBody *string) http.HandlerFunc {
	t.Helper()
	return func(w http.ResponseWriter, r *http.Request) {
		body, err := io.ReadAll(r.Body)
		if err != nil {
			http.Error(w, "read error", 500)
			return
		}
		if capturedBody != nil {
			*capturedBody = string(body)
		}
		resp := map[string]interface{}{
			"images": []map[string]interface{}{
				{"url": imageServer.URL + "/image.png"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}
}

// --- Tests ---

// RT-1.1: No arguments exits non-zero with usage on stderr.
// User action: types "generate-image" with no arguments.
// User observes: error message on terminal, non-zero exit.
func TestCLI_no_args_exits_nonzero_with_usage_RT1_1(t *testing.T) {
	bin := buildBinary(t)
	linkPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, linkPath, []string{}, "", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit code, got 0")
	}
	if !strings.Contains(strings.ToLower(stderr), "usage") {
		t.Errorf("Expected usage message on stderr, got: %q", stderr)
	}
}

// RT-1.2: Empty stdin exits non-zero with error on stderr.
// User action: runs "echo '' | generate-image out.png".
// User observes: error about empty prompt on terminal.
func TestCLI_empty_stdin_exits_nonzero_RT1_2(t *testing.T) {
	bin := buildBinary(t)
	linkPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, linkPath, []string{"out.png"}, "", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit code, got 0")
	}
	if stderr == "" {
		t.Errorf("Expected error message on stderr, got nothing")
	}
}

// RT-1.3: Whitespace-only stdin exits non-zero with error on stderr.
// User action: runs "echo '   ' | generate-image out.png".
// User observes: error about empty prompt on terminal.
func TestCLI_whitespace_stdin_exits_nonzero_RT1_3(t *testing.T) {
	bin := buildBinary(t)
	linkPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, linkPath, []string{"out.png"}, "   \n\t  \n", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit code, got 0")
	}
	if stderr == "" {
		t.Errorf("Expected error message on stderr, got nothing")
	}
}

// RT-1.4: Missing FAL_KEY exits non-zero with clear error.
// User action: runs the tool without a .env file.
// User observes: error about missing API key on terminal.
func TestCLI_missing_fal_key_exits_nonzero_RT1_4(t *testing.T) {
	bin := buildBinary(t)
	// No FAL_KEY in .env
	linkPath := setupEnv(t, bin, "", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, linkPath, []string{"out.png"}, "a red cat", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit code, got 0")
	}
	lower := strings.ToLower(stderr)
	if !strings.Contains(lower, "fal_key") && !strings.Contains(lower, "api key") && !strings.Contains(lower, "fal key") {
		t.Errorf("Expected error mentioning FAL_KEY or API key, got: %q", stderr)
	}
}

// RT-1.5: Missing config.yaml exits non-zero with clear error.
// User action: runs the tool without a config.yaml file.
// User observes: error about missing config on terminal.
func TestCLI_missing_config_exits_nonzero_RT1_5(t *testing.T) {
	bin := buildBinary(t)
	// No config.yaml
	linkPath := setupEnv(t, bin, "test-key", "")

	_, stderr, exitCode := runBinary(t, linkPath, []string{"out.png"}, "a red cat", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit code, got 0")
	}
	lower := strings.ToLower(stderr)
	if !strings.Contains(lower, "config") {
		t.Errorf("Expected error mentioning config, got: %q", stderr)
	}
}

// RT-1.6: FAL_KEY loaded from .env next to binary, not from cwd.
// User action: runs tool from /tmp where a decoy .env exists with a different key.
// User observes: the tool uses the key from its own directory, not /tmp.
func TestCLI_env_loaded_from_binary_dir_not_cwd_RT1_6(t *testing.T) {
	bin := buildBinary(t)

	// Set up the real env next to binary with a known key
	realKey := "real-key-from-binary-dir"
	binPath := setupEnv(t, bin, realKey, "model: fal-ai/grok-2-aurora\n")

	// Create a decoy .env in a different cwd with a wrong key
	cwd := t.TempDir()
	decoyKey := "decoy-key-from-cwd"
	os.WriteFile(filepath.Join(cwd, ".env"), []byte(fmt.Sprintf("FAL_KEY=%s\n", decoyKey)), 0600)

	// Start fake API that records the auth header
	var capturedAuth string
	imageServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write(fakeImagePNG)
	}))
	t.Cleanup(imageServer.Close)

	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		capturedAuth = r.Header.Get("Authorization")
		resp := map[string]interface{}{
			"images": []map[string]interface{}{
				{"url": imageServer.URL + "/image.png"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")

	cmd := exec.Command(binPath, outFile)
	cmd.Stdin = strings.NewReader("a red cat")
	cmd.Dir = cwd
	cmd.Env = append(os.Environ(), "FAL_BASE_URL="+server.URL)
	cmd.Run()

	expectedAuth := "Key " + realKey
	if capturedAuth != expectedAuth {
		t.Errorf("Expected auth header %q (from binary dir), got %q", expectedAuth, capturedAuth)
	}
}

// RT-1.7: Model read from config.yaml next to binary.
// User action: sets model to a specific value in config.yaml.
// User observes: that model is what the FAL API receives.
func TestCLI_model_from_config_yaml_RT1_7(t *testing.T) {
	bin := buildBinary(t)
	customModel := "fal-ai/test-model-xyz"
	linkPath := setupEnv(t, bin, "test-key", fmt.Sprintf("model: %s\n", customModel))

	var capturedPath string
	imageServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write(fakeImagePNG)
	}))
	t.Cleanup(imageServer.Close)

	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		capturedPath = r.URL.Path
		resp := map[string]interface{}{
			"images": []map[string]interface{}{
				{"url": imageServer.URL + "/image.png"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	runBinary(t, linkPath, []string{outFile}, "a red cat", []string{"FAL_BASE_URL=" + server.URL})

	if !strings.Contains(capturedPath, customModel) {
		t.Errorf("Expected request path to contain model %q, got path: %q", customModel, capturedPath)
	}
}

// RT-1.8: Prompt text piped to stdin is passed to the FAL API.
// User action: pipes "a red cat sitting on a wall" to the tool.
// User observes: that exact prompt is sent to FAL.
func TestCLI_prompt_passed_to_api_RT1_8(t *testing.T) {
	bin := buildBinary(t)
	linkPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	var capturedBody string
	imageServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write(fakeImagePNG)
	}))
	t.Cleanup(imageServer.Close)

	server := startFakeAPI(t, successHandler(t, imageServer, &capturedBody), nil)

	prompt := "a red cat sitting on a wall"
	outFile := filepath.Join(t.TempDir(), "out.png")
	runBinary(t, linkPath, []string{outFile}, prompt, []string{"FAL_BASE_URL=" + server.URL})

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(capturedBody), &parsed); err != nil {
		t.Fatalf("Failed to parse captured request body: %v", err)
	}
	if parsed["prompt"] != prompt {
		t.Errorf("Expected prompt %q in request body, got %q", prompt, parsed["prompt"])
	}
}

// RT-1.9: Successful generation writes a non-empty image file at the output path.
// User action: pipes a prompt and provides an output filename.
// User observes: an image file appears at that path.
func TestCLI_success_writes_image_file_RT1_9(t *testing.T) {
	bin := buildBinary(t)
	linkPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	imageServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write(fakeImagePNG)
	}))
	t.Cleanup(imageServer.Close)

	server := startFakeAPI(t, successHandler(t, imageServer, nil), nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, _, exitCode := runBinary(t, linkPath, []string{outFile}, "a red cat", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit code 0, got %d", exitCode)
	}

	info, err := os.Stat(outFile)
	if err != nil {
		t.Fatalf("Output file does not exist: %v", err)
	}
	if info.Size() == 0 {
		t.Errorf("Output file is empty")
	}
	// Verify it's a valid PNG (starts with PNG magic bytes)
	data, _ := os.ReadFile(outFile)
	if len(data) < 4 || string(data[:4]) != "\x89PNG" {
		t.Errorf("Output file does not appear to be a valid PNG")
	}
}

// RT-1.10: FAL API error exits non-zero with error on stderr.
// User action: FAL API returns an error (e.g. server error).
// User observes: error message on terminal, no file created.
func TestCLI_api_error_exits_nonzero_RT1_10(t *testing.T) {
	bin := buildBinary(t)
	linkPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		http.Error(w, `{"detail": "model not found"}`, http.StatusBadRequest)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, linkPath, []string{outFile}, "a red cat", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit code, got 0")
	}
	if stderr == "" {
		t.Errorf("Expected error message on stderr, got nothing")
	}
	// Output file should not exist
	if _, err := os.Stat(outFile); err == nil {
		t.Errorf("Output file should not exist after API error")
	}
}

// RT-1.11: --help flag prints usage and exits zero.
// User action: runs "generate-image --help".
// User observes: usage information printed, clean exit.
func TestCLI_help_flag_prints_usage_RT1_11(t *testing.T) {
	bin := buildBinary(t)
	linkPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	// --help should work without stdin
	_, stderr, exitCode := runBinary(t, linkPath, []string{"--help"}, "", nil)

	if exitCode != 0 {
		t.Errorf("Expected exit code 0 for --help, got %d", exitCode)
	}
	lower := strings.ToLower(stderr)
	if !strings.Contains(lower, "usage") {
		t.Errorf("Expected usage text for --help, got: %q", stderr)
	}
}

// RT-1.12: --version flag prints version and exits zero.
// User action: runs "generate-image --version".
// User observes: version string printed, clean exit.
func TestCLI_version_flag_prints_version_RT1_12(t *testing.T) {
	bin := buildBinary(t)
	linkPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, linkPath, []string{"--version"}, "", nil)

	if exitCode != 0 {
		t.Errorf("Expected exit code 0 for --version, got %d", exitCode)
	}
	if stderr == "" {
		t.Errorf("Expected version output, got nothing")
	}
}

// RT-1.13: Cost printed to stderr when pricing data is available.
// User action: generates an image with a model that has pricing data.
// User observes: cost line like "Cost: $0.07 (per image)" on terminal.
func TestCLI_cost_printed_when_available_RT1_13(t *testing.T) {
	bin := buildBinary(t)
	linkPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	imageServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write(fakeImagePNG)
	}))
	t.Cleanup(imageServer.Close)

	pricingHandler := func(w http.ResponseWriter, r *http.Request) {
		resp := map[string]interface{}{
			"prices": []map[string]interface{}{
				{
					"unit_price": 0.07,
					"unit":       "image",
					"currency":   "USD",
				},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}

	server := startFakeAPI(t, successHandler(t, imageServer, nil), pricingHandler)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, _ := runBinary(t, linkPath, []string{outFile}, "a red cat", []string{"FAL_BASE_URL=" + server.URL})

	lower := strings.ToLower(stderr)
	if !strings.Contains(lower, "cost") {
		t.Errorf("Expected cost information on stderr, got: %q", stderr)
	}
	if !strings.Contains(stderr, "0.07") {
		t.Errorf("Expected cost amount on stderr, got: %q", stderr)
	}
}

// RT-1.14: No cost line on stderr when pricing data is unavailable.
// User action: generates an image with a model that has no pricing data.
// User observes: no cost line on terminal.
func TestCLI_no_cost_when_unavailable_RT1_14(t *testing.T) {
	bin := buildBinary(t)
	linkPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	imageServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write(fakeImagePNG)
	}))
	t.Cleanup(imageServer.Close)

	// Pricing endpoint returns empty prices
	pricingHandler := func(w http.ResponseWriter, r *http.Request) {
		resp := map[string]interface{}{
			"prices": []interface{}{},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}

	server := startFakeAPI(t, successHandler(t, imageServer, nil), pricingHandler)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, _ := runBinary(t, linkPath, []string{outFile}, "a red cat", []string{"FAL_BASE_URL=" + server.URL})

	if strings.Contains(stderr, "Cost:") {
		t.Errorf("Expected no cost line on stderr when pricing unavailable, got: %q", stderr)
	}
}

// RT-1.15: No extension given -- file written with API format extension.
// User action: runs "echo 'a cat' | generate-image sunset" (no extension).
// User observes: file written as sunset.jpg (or whatever format the API returns).
func TestCLI_no_extension_writes_api_format_RT1_15(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	imageServer := newImageServer(t, fakeImageJPEG, "image/jpeg")
	server := startFakeAPI(t, successHandler(t, imageServer, nil), nil)

	outDir := t.TempDir()
	outFile := filepath.Join(outDir, "sunset")
	_, _, exitCode := runBinary(t, binPath, []string{outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit code 0, got %d", exitCode)
	}

	// Should have written sunset.jpg
	expectedPath := filepath.Join(outDir, "sunset.jpg")
	if _, err := os.Stat(expectedPath); err != nil {
		// Check what files exist
		entries, _ := os.ReadDir(outDir)
		names := make([]string, 0, len(entries))
		for _, e := range entries {
			names = append(names, e.Name())
		}
		t.Fatalf("Expected %s to exist, found: %v", expectedPath, names)
	}
}

// RT-1.16: Matching extension given -- file written as-is.
// User action: runs "echo 'a cat' | generate-image sunset.jpg" and API returns JPEG.
// User observes: file written as sunset.jpg, no conversion needed.
func TestCLI_matching_extension_writes_as_is_RT1_16(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	imageServer := newImageServer(t, fakeImageJPEG, "image/jpeg")
	server := startFakeAPI(t, successHandler(t, imageServer, nil), nil)

	outDir := t.TempDir()
	outFile := filepath.Join(outDir, "sunset.jpg")
	_, _, exitCode := runBinary(t, binPath, []string{outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit code 0, got %d", exitCode)
	}

	info, err := os.Stat(outFile)
	if err != nil {
		t.Fatalf("Expected %s to exist: %v", outFile, err)
	}
	if info.Size() == 0 {
		t.Errorf("Output file is empty")
	}
}

// RT-1.17: Mismatched extension with magick available -- file converted.
// User action: runs "echo 'a cat' | generate-image sunset.jpg" and API returns PNG.
// User observes: file written as sunset.jpg (converted via magick).
func TestCLI_mismatched_extension_with_magick_converts_RT1_17(t *testing.T) {
	// Skip if magick is not available
	if _, err := exec.LookPath("magick"); err != nil {
		t.Skip("ImageMagick (magick) not available on PATH")
	}

	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	// API returns PNG, user requests .jpg -- conversion needed.
	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, successHandler(t, imageServer, nil), nil)

	outDir := t.TempDir()
	outFile := filepath.Join(outDir, "sunset.jpg")
	_, stderr, exitCode := runBinary(t, binPath, []string{outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Fatalf("Expected exit code 0, got %d; stderr: %s", exitCode, stderr)
	}

	data, err := os.ReadFile(outFile)
	if err != nil {
		t.Fatalf("Expected %s to exist: %v", outFile, err)
	}
	// Verify it's actually a JPEG (magic bytes), not PNG
	if len(data) < 2 || data[0] != 0xff || data[1] != 0xd8 {
		t.Errorf("Expected JPEG file after conversion, got different format (first bytes: %x)", data[:4])
	}
}

// RT-1.18: Mismatched extension without magick -- exits non-zero with clear error.
// User action: runs "echo 'a cat' | generate-image sunset.jpg" and API returns PNG,
// but magick is not on PATH.
// User observes: error message about format mismatch on terminal.
func TestCLI_mismatched_extension_without_magick_fails_RT1_18(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, successHandler(t, imageServer, nil), nil)

	outDir := t.TempDir()
	outFile := filepath.Join(outDir, "sunset.jpg")

	// Set PATH to empty so magick cannot be found
	_, stderr, exitCode := runBinary(t, binPath, []string{outFile}, "a cat", []string{
		"FAL_BASE_URL=" + server.URL,
		"PATH=",
	})

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit code when magick unavailable and format mismatched")
	}
	if stderr == "" {
		t.Errorf("Expected error message on stderr")
	}

	// The requested file should not exist (or should not be the wrong format)
	if _, err := os.Stat(outFile); err == nil {
		t.Errorf("Output file should not exist after conversion failure")
	}
}

// --- Key resolution chain tests ---

// setupEnvWithConfig is like setupEnv but takes full config YAML and
// optionally skips writing .env (to test key resolution from config).
func setupEnvWithConfig(t *testing.T, binary string, dotEnvContent string, configYAML string) string {
	t.Helper()
	tmpDir := t.TempDir()

	copyPath := filepath.Join(tmpDir, "generate-image")
	srcData, err := os.ReadFile(binary)
	if err != nil {
		t.Fatalf("Failed to read binary: %v", err)
	}
	if err := os.WriteFile(copyPath, srcData, 0755); err != nil {
		t.Fatalf("Failed to copy binary: %v", err)
	}

	// Write .env (may be empty to block fallback to ~/.config)
	if err := os.WriteFile(filepath.Join(tmpDir, ".env"), []byte(dotEnvContent), 0600); err != nil {
		t.Fatalf("Failed to write .env: %v", err)
	}

	if configYAML != "" {
		if err := os.WriteFile(filepath.Join(tmpDir, "config.yaml"), []byte(configYAML), 0644); err != nil {
			t.Fatalf("Failed to write config.yaml: %v", err)
		}
	}

	return copyPath
}

// RT-1.19: FAL_KEY env var takes priority over all other sources.
// User action: sets FAL_KEY in shell, config also has a command/file.
// User observes: the env var key is used, not the config one.
func TestCLI_env_var_takes_priority_RT1_19(t *testing.T) {
	bin := buildBinary(t)

	// Config points to a file with a different key
	tmpDir := t.TempDir()
	keyFile := filepath.Join(tmpDir, "fal.key")
	os.WriteFile(keyFile, []byte("file-key\n"), 0600)

	configYAML := fmt.Sprintf("model: fal-ai/grok-2-aurora\napi-keys:\n  fal:\n    file: %s\n", keyFile)
	binPath := setupEnvWithConfig(t, bin, "", configYAML)

	var capturedAuth string
	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		capturedAuth = r.Header.Get("Authorization")
		resp := map[string]interface{}{
			"images": []map[string]interface{}{
				{"url": imageServer.URL + "/image.png"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	runBinary(t, binPath, []string{outFile}, "a cat", []string{
		"FAL_BASE_URL=" + server.URL,
		"FAL_KEY=env-var-key",
	})

	if capturedAuth != "Key env-var-key" {
		t.Errorf("Expected env var key to take priority, got auth header: %q", capturedAuth)
	}
}

// RT-1.20: api-keys.fal.command in config.yaml provides the key.
// User action: config has a command that outputs the key.
// User observes: the command's output is used as the key.
func TestCLI_config_command_provides_key_RT1_20(t *testing.T) {
	bin := buildBinary(t)

	configYAML := "model: fal-ai/grok-2-aurora\napi-keys:\n  fal:\n    command: echo command-key\n"
	binPath := setupEnvWithConfig(t, bin, "", configYAML)

	var capturedAuth string
	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		capturedAuth = r.Header.Get("Authorization")
		resp := map[string]interface{}{
			"images": []map[string]interface{}{
				{"url": imageServer.URL + "/image.png"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	runBinary(t, binPath, []string{outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if capturedAuth != "Key command-key" {
		t.Errorf("Expected command key, got auth header: %q", capturedAuth)
	}
}

// RT-1.21: api-keys.fal.file in config.yaml provides the key.
// User action: config points to a key file.
// User observes: the key from that file is used.
func TestCLI_config_file_provides_key_RT1_21(t *testing.T) {
	bin := buildBinary(t)

	tmpDir := t.TempDir()
	keyFile := filepath.Join(tmpDir, "fal.key")
	os.WriteFile(keyFile, []byte("file-provided-key\n"), 0600)

	configYAML := fmt.Sprintf("model: fal-ai/grok-2-aurora\napi-keys:\n  fal:\n    file: %s\n", keyFile)
	binPath := setupEnvWithConfig(t, bin, "", configYAML)

	var capturedAuth string
	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		capturedAuth = r.Header.Get("Authorization")
		resp := map[string]interface{}{
			"images": []map[string]interface{}{
				{"url": imageServer.URL + "/image.png"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	runBinary(t, binPath, []string{outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if capturedAuth != "Key file-provided-key" {
		t.Errorf("Expected file key, got auth header: %q", capturedAuth)
	}
}

// RT-1.22: command takes priority over file when both specified.
// User action: config has both command and file for fal key.
// User observes: the command's output is used.
func TestCLI_command_beats_file_RT1_22(t *testing.T) {
	bin := buildBinary(t)

	tmpDir := t.TempDir()
	keyFile := filepath.Join(tmpDir, "fal.key")
	os.WriteFile(keyFile, []byte("file-key\n"), 0600)

	configYAML := fmt.Sprintf("model: fal-ai/grok-2-aurora\napi-keys:\n  fal:\n    command: echo command-wins\n    file: %s\n", keyFile)
	binPath := setupEnvWithConfig(t, bin, "", configYAML)

	var capturedAuth string
	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		capturedAuth = r.Header.Get("Authorization")
		resp := map[string]interface{}{
			"images": []map[string]interface{}{
				{"url": imageServer.URL + "/image.png"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	runBinary(t, binPath, []string{outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if capturedAuth != "Key command-wins" {
		t.Errorf("Expected command key to win over file, got auth header: %q", capturedAuth)
	}
}

// RT-1.23: .env fallback used when no config key sources defined.
// User action: config has no api-keys section, .env has the key.
// User observes: .env key is used (backward compatible).
func TestCLI_dotenv_fallback_RT1_23(t *testing.T) {
	bin := buildBinary(t)

	binPath := setupEnvWithConfig(t, bin, "FAL_KEY=dotenv-fallback-key\n", "model: fal-ai/grok-2-aurora\n")

	var capturedAuth string
	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		capturedAuth = r.Header.Get("Authorization")
		resp := map[string]interface{}{
			"images": []map[string]interface{}{
				{"url": imageServer.URL + "/image.png"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	runBinary(t, binPath, []string{outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if capturedAuth != "Key dotenv-fallback-key" {
		t.Errorf("Expected .env fallback key, got auth header: %q", capturedAuth)
	}
}

// --- --quiet, --dry-run, --preview tests ---

// RT-1.24: --quiet suppresses cost output on stderr.
// User action: runs with --quiet flag and a model that has pricing.
// User observes: no cost line on terminal.
func TestCLI_quiet_suppresses_cost_RT1_24(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	imageServer := newImageServer(t, fakeImagePNG, "image/png")

	pricingHandler := func(w http.ResponseWriter, r *http.Request) {
		resp := map[string]interface{}{
			"prices": []map[string]interface{}{
				{"unit_price": 0.07, "unit": "image", "currency": "USD"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}
	server := startFakeAPI(t, successHandler(t, imageServer, nil), pricingHandler)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, binPath, []string{"--quiet", outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit code 0, got %d", exitCode)
	}
	if strings.Contains(strings.ToLower(stderr), "cost") {
		t.Errorf("Expected no cost output with --quiet, got: %q", stderr)
	}
}

// RT-1.25: cost printed by default (without --quiet).
// User action: runs without --quiet flag and a model that has pricing.
// User observes: cost line on terminal.
func TestCLI_cost_printed_by_default_RT1_25(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	imageServer := newImageServer(t, fakeImagePNG, "image/png")

	pricingHandler := func(w http.ResponseWriter, r *http.Request) {
		resp := map[string]interface{}{
			"prices": []map[string]interface{}{
				{"unit_price": 0.07, "unit": "image", "currency": "USD"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}
	server := startFakeAPI(t, successHandler(t, imageServer, nil), pricingHandler)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, _ := runBinary(t, binPath, []string{outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if !strings.Contains(strings.ToLower(stderr), "cost") {
		t.Errorf("Expected cost output by default, got: %q", stderr)
	}
}

// RT-1.26: --dry-run prints config summary and exits zero without calling API.
// User action: runs with --dry-run flag.
// User observes: summary of what would happen (model, prompt, output), no API call.
func TestCLI_dry_run_prints_summary_RT1_26(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	apiCalled := false
	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		apiCalled = true
		http.Error(w, "should not be called", 500)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, binPath, []string{"--dry-run", outFile}, "a red cat", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit code 0 for --dry-run, got %d", exitCode)
	}
	if apiCalled {
		t.Errorf("API should not be called during --dry-run")
	}
	lower := strings.ToLower(stderr)
	if !strings.Contains(lower, "model") {
		t.Errorf("Expected --dry-run to mention model, got: %q", stderr)
	}
	if !strings.Contains(lower, "a red cat") {
		t.Errorf("Expected --dry-run to show prompt, got: %q", stderr)
	}
}

// RT-1.27: --dry-run does not create an output file.
// User action: runs with --dry-run flag.
// User observes: no output file created.
func TestCLI_dry_run_no_output_file_RT1_27(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	server := startFakeAPI(t, nil, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	runBinary(t, binPath, []string{"--dry-run", outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if _, err := os.Stat(outFile); err == nil {
		t.Errorf("Output file should not exist after --dry-run")
	}
}

// RT-1.28: --preview opens the image with the configured preview_command.
// User action: runs with --preview flag and preview_command set in config.
// User observes: image generated, then opened with the configured command.
func TestCLI_preview_opens_image_RT1_28(t *testing.T) {
	bin := buildBinary(t)

	// Use a preview command that writes a marker file to prove it ran.
	markerFile := filepath.Join(t.TempDir(), "preview-ran")
	previewCmd := fmt.Sprintf("touch %s", markerFile)
	configYAML := fmt.Sprintf("model: fal-ai/grok-2-aurora\npreview_command: \"%s\"\n", previewCmd)
	binPath := setupEnv(t, bin, "test-key", configYAML)

	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, successHandler(t, imageServer, nil), nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, _, exitCode := runBinary(t, binPath, []string{"--preview", outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit code 0, got %d", exitCode)
	}
	if _, err := os.Stat(markerFile); err != nil {
		t.Errorf("Preview command did not run (marker file missing)")
	}
}

// RT-1.29: --preview without preview_command uses platform default.
// User action: runs with --preview flag but no preview_command in config.
// User observes: image generated, platform default viewer invoked (which may
// fail in test env, but the binary should attempt it rather than error about config).
func TestCLI_preview_without_config_uses_default_RT1_29(t *testing.T) {
	bin := buildBinary(t)

	// Use a config with preview_command that writes a marker to prove default is overridden.
	// Then test WITHOUT preview_command -- the binary should not error about missing config.
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, successHandler(t, imageServer, nil), nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, binPath, []string{"--preview", outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	// The default preview command (open/xdg-open) may fail in a headless test env,
	// but the error should be about the preview command failing, NOT about
	// missing preview_command configuration.
	if exitCode != 0 {
		lower := strings.ToLower(stderr)
		if strings.Contains(lower, "requires preview_command") {
			t.Errorf("Should use platform default, not require config; got: %q", stderr)
		}
	}
}

// RT-1.30: --quiet and --dry-run together exits non-zero.
// User action: runs with both --quiet and --dry-run.
// User observes: error about conflicting flags.
func TestCLI_quiet_and_dry_run_conflict_RT1_30(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, binPath, []string{"--quiet", "--dry-run", "out.png"}, "a cat", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit code for --quiet + --dry-run")
	}
	if stderr == "" {
		t.Errorf("Expected error message about conflicting flags")
	}
}
