// ABOUTME: Regression tests for the pix CLI.
// ABOUTME: Each test runs the compiled binary as a subprocess, matching the real user entry point.

package regression

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"testing"
)

var (
	binaryPath string
	buildOnce  sync.Once
	buildErr   error
)

// buildBinary compiles the CLI binary once for all tests.
func buildBinary(t *testing.T) string {
	t.Helper()
	buildOnce.Do(func() {
		tmpDir := os.TempDir()
		binaryPath = filepath.Join(tmpDir, "pix-test")
		cmd := exec.Command("go", "build", "-o", binaryPath, ".")
		cmd.Dir = filepath.Join(projectRoot())
		out, err := cmd.CombinedOutput()
		if err != nil {
			buildErr = fmt.Errorf("build failed: %s\n%s", err, out)
		}
	})
	if buildErr != nil {
		t.Fatalf("Failed to build binary: %v", buildErr)
	}
	return binaryPath
}

// projectRoot returns the root of the project (two levels up from this test file).
func projectRoot() string {
	// tests/regression/ -> project root
	dir, _ := os.Getwd()
	return filepath.Join(dir, "..", "..")
}

// setupEnv creates a temp directory with .env and config.yaml next to a copy
// of the binary, so the binary resolves config from its own directory.
// Thin wrapper around setupEnvWithConfig for the common case.
func setupEnv(t *testing.T, binary string, falKey string, configYAML string) string {
	t.Helper()
	dotEnv := ""
	if falKey != "" {
		dotEnv = fmt.Sprintf("FAL_KEY=%s\n", falKey)
	}
	return setupEnvWithConfig(t, binary, dotEnv, configYAML)
}

// runBinary executes the binary with the given args, stdin, and env vars.
// Returns stdout, stderr, and the exit code.
func runBinary(t *testing.T, binPath string, args []string, stdin string, env []string) (string, string, int) {
	t.Helper()
	cmd := exec.Command(binPath, args...)
	if stdin != "" {
		cmd.Stdin = strings.NewReader(stdin)
	} else {
		// Explicitly provide empty stdin (closed pipe, not terminal)
		cmd.Stdin = strings.NewReader("")
	}
	var stdout, stderr strings.Builder
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	cmd.Env = append(os.Environ(), env...)

	err := cmd.Run()
	exitCode := 0
	if exitErr, ok := err.(*exec.ExitError); ok {
		exitCode = exitErr.ExitCode()
	} else if err != nil {
		t.Fatalf("Failed to run binary: %v", err)
	}

	return stdout.String(), stderr.String(), exitCode
}

// startFakeAPI starts a test HTTP server that mimics the FAL API.
// generateHandler handles the image generation endpoint.
// pricingHandler handles the pricing endpoint (nil = 404).
// Returns the server and its URL.
func startFakeAPI(t *testing.T, generateHandler http.HandlerFunc, pricingHandler http.HandlerFunc) *httptest.Server {
	t.Helper()
	mux := http.NewServeMux()
	// Catch-all for generation endpoints (any model path)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		if strings.HasPrefix(r.URL.Path, "/v1/models/pricing") {
			if pricingHandler != nil {
				pricingHandler(w, r)
			} else {
				http.NotFound(w, r)
			}
			return
		}
		if generateHandler != nil {
			generateHandler(w, r)
		} else {
			http.NotFound(w, r)
		}
	})
	server := httptest.NewServer(mux)
	t.Cleanup(server.Close)
	return server
}

// fakeImagePNG is a valid 1x1 red PNG generated by ImageMagick.
var fakeImagePNG = []byte{
	0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d,
	0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
	0x01, 0x03, 0x00, 0x00, 0x00, 0x25, 0xdb, 0x56, 0xca, 0x00, 0x00, 0x00,
	0x06, 0x50, 0x4c, 0x54, 0x45, 0xff, 0x00, 0x00, 0xff, 0xff, 0xff, 0x41,
	0x1d, 0x34, 0x11, 0x00, 0x00, 0x00, 0x0a, 0x49, 0x44, 0x41, 0x54, 0x08,
	0xd7, 0x63, 0x60, 0x00, 0x00, 0x00, 0x02, 0x00, 0x01, 0xe2, 0x21, 0xbc,
	0x33, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4e, 0x44, 0xae, 0x42, 0x60,
	0x82,
}

// fakeImageJPEG is a minimal valid JPEG (1x1 pixel).
var fakeImageJPEG = []byte{
	0xff, 0xd8, 0xff, 0xe0, 0x00, 0x10, 0x4a, 0x46, 0x49, 0x46, 0x00, 0x01,
	0x01, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0xff, 0xd9,
}

// newImageServer creates an httptest server that serves fake image bytes with the given content type.
func newImageServer(t *testing.T, imageBytes []byte, contentType string) *httptest.Server {
	t.Helper()
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", contentType)
		w.Write(imageBytes)
	}))
	t.Cleanup(server.Close)
	return server
}

// successHandler returns a handler that serves a fake image and records the request.
func successHandler(t *testing.T, imageServer *httptest.Server, capturedBody *string) http.HandlerFunc {
	t.Helper()
	return func(w http.ResponseWriter, r *http.Request) {
		body, err := io.ReadAll(r.Body)
		if err != nil {
			http.Error(w, "read error", 500)
			return
		}
		if capturedBody != nil {
			*capturedBody = string(body)
		}
		resp := map[string]interface{}{
			"images": []map[string]interface{}{
				{"url": imageServer.URL + "/image.png"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}
}

// --- Tests ---

// RT-1.1: gen-img with no positional args exits non-zero with usage on stderr.
// User action: types "pix gen-img" without specifying an output file.
// User observes: error message on terminal, non-zero exit.
func TestCLI_no_args_exits_nonzero_with_usage_RT1_1(t *testing.T) {
	bin := buildBinary(t)
	linkPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, linkPath, []string{"gen-img"}, "", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit code, got 0")
	}
	if !strings.Contains(strings.ToLower(stderr), "usage") {
		t.Errorf("Expected usage message on stderr, got: %q", stderr)
	}
}

// RT-1.2: Empty stdin exits non-zero with error on stderr.
// User action: runs "echo '' | generate-image out.png".
// User observes: error about empty prompt on terminal.
func TestCLI_empty_stdin_exits_nonzero_RT1_2(t *testing.T) {
	bin := buildBinary(t)
	linkPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, linkPath, []string{"gen-img", "out.png"}, "", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit code, got 0")
	}
	if stderr == "" {
		t.Errorf("Expected error message on stderr, got nothing")
	}
}

// RT-1.3: Whitespace-only stdin exits non-zero with error on stderr.
// User action: runs "echo '   ' | generate-image out.png".
// User observes: error about empty prompt on terminal.
func TestCLI_whitespace_stdin_exits_nonzero_RT1_3(t *testing.T) {
	bin := buildBinary(t)
	linkPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, linkPath, []string{"gen-img", "out.png"}, "   \n\t  \n", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit code, got 0")
	}
	if stderr == "" {
		t.Errorf("Expected error message on stderr, got nothing")
	}
}

// RT-1.4: Missing FAL_KEY exits non-zero with clear error.
// User action: runs the tool without a .env file.
// User observes: error about missing API key on terminal.
func TestCLI_missing_fal_key_exits_nonzero_RT1_4(t *testing.T) {
	bin := buildBinary(t)
	// No FAL_KEY in .env
	linkPath := setupEnv(t, bin, "", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, linkPath, []string{"gen-img", "out.png"}, "a red cat", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit code, got 0")
	}
	lower := strings.ToLower(stderr)
	if !strings.Contains(lower, "fal_key") && !strings.Contains(lower, "api key") && !strings.Contains(lower, "fal key") {
		t.Errorf("Expected error mentioning FAL_KEY or API key, got: %q", stderr)
	}
}

// RT-1.5: Missing config.yaml exits non-zero with clear error.
// User action: runs the tool without a config.yaml file.
// User observes: error about missing config on terminal.
func TestCLI_missing_config_exits_nonzero_RT1_5(t *testing.T) {
	bin := buildBinary(t)
	// No config.yaml
	linkPath := setupEnv(t, bin, "test-key", "")

	_, stderr, exitCode := runBinary(t, linkPath, []string{"gen-img", "out.png"}, "a red cat", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit code, got 0")
	}
	lower := strings.ToLower(stderr)
	if !strings.Contains(lower, "config") {
		t.Errorf("Expected error mentioning config, got: %q", stderr)
	}
}

// RT-1.6: FAL_KEY loaded from .env next to binary, not from cwd.
// User action: runs tool from /tmp where a decoy .env exists with a different key.
// User observes: the tool uses the key from its own directory, not /tmp.
func TestCLI_env_loaded_from_binary_dir_not_cwd_RT1_6(t *testing.T) {
	bin := buildBinary(t)

	// Set up the real env next to binary with a known key
	realKey := "real-key-from-binary-dir"
	binPath := setupEnv(t, bin, realKey, "model: fal-ai/grok-2-aurora\n")

	// Create a decoy .env in a different cwd with a wrong key
	cwd := t.TempDir()
	decoyKey := "decoy-key-from-cwd"
	os.WriteFile(filepath.Join(cwd, ".env"), []byte(fmt.Sprintf("FAL_KEY=%s\n", decoyKey)), 0600)

	// Start fake API that records the auth header
	var capturedAuth string
	imageServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write(fakeImagePNG)
	}))
	t.Cleanup(imageServer.Close)

	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		capturedAuth = r.Header.Get("Authorization")
		resp := map[string]interface{}{
			"images": []map[string]interface{}{
				{"url": imageServer.URL + "/image.png"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")

	cmd := exec.Command(binPath, "gen-img", outFile)
	cmd.Stdin = strings.NewReader("a red cat")
	cmd.Dir = cwd
	cmd.Env = append(os.Environ(), "FAL_BASE_URL="+server.URL)
	cmd.Run()

	expectedAuth := "Key " + realKey
	if capturedAuth != expectedAuth {
		t.Errorf("Expected auth header %q (from binary dir), got %q", expectedAuth, capturedAuth)
	}
}

// RT-1.7: Model read from config.yaml next to binary.
// User action: sets model to a specific value in config.yaml.
// User observes: that model is what the FAL API receives.
func TestCLI_model_from_config_yaml_RT1_7(t *testing.T) {
	bin := buildBinary(t)
	customModel := "fal-ai/test-model-xyz"
	linkPath := setupEnv(t, bin, "test-key", fmt.Sprintf("model: %s\n", customModel))

	var capturedPath string
	imageServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write(fakeImagePNG)
	}))
	t.Cleanup(imageServer.Close)

	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		capturedPath = r.URL.Path
		resp := map[string]interface{}{
			"images": []map[string]interface{}{
				{"url": imageServer.URL + "/image.png"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	runBinary(t, linkPath, []string{"gen-img", outFile}, "a red cat", []string{"FAL_BASE_URL=" + server.URL})

	if !strings.Contains(capturedPath, customModel) {
		t.Errorf("Expected request path to contain model %q, got path: %q", customModel, capturedPath)
	}
}

// RT-1.8: Prompt text piped to stdin is passed to the FAL API.
// User action: pipes "a red cat sitting on a wall" to the tool.
// User observes: that exact prompt is sent to FAL.
func TestCLI_prompt_passed_to_api_RT1_8(t *testing.T) {
	bin := buildBinary(t)
	linkPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	var capturedBody string
	imageServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write(fakeImagePNG)
	}))
	t.Cleanup(imageServer.Close)

	server := startFakeAPI(t, successHandler(t, imageServer, &capturedBody), nil)

	prompt := "a red cat sitting on a wall"
	outFile := filepath.Join(t.TempDir(), "out.png")
	runBinary(t, linkPath, []string{"gen-img", outFile}, prompt, []string{"FAL_BASE_URL=" + server.URL})

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(capturedBody), &parsed); err != nil {
		t.Fatalf("Failed to parse captured request body: %v", err)
	}
	if parsed["prompt"] != prompt {
		t.Errorf("Expected prompt %q in request body, got %q", prompt, parsed["prompt"])
	}
}

// RT-1.9: Successful generation writes a non-empty image file at the output path.
// User action: pipes a prompt and provides an output filename.
// User observes: an image file appears at that path.
func TestCLI_success_writes_image_file_RT1_9(t *testing.T) {
	bin := buildBinary(t)
	linkPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	imageServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write(fakeImagePNG)
	}))
	t.Cleanup(imageServer.Close)

	server := startFakeAPI(t, successHandler(t, imageServer, nil), nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, _, exitCode := runBinary(t, linkPath, []string{"gen-img", outFile}, "a red cat", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit code 0, got %d", exitCode)
	}

	info, err := os.Stat(outFile)
	if err != nil {
		t.Fatalf("Output file does not exist: %v", err)
	}
	if info.Size() == 0 {
		t.Errorf("Output file is empty")
	}
	// Verify it's a valid PNG (starts with PNG magic bytes)
	data, _ := os.ReadFile(outFile)
	if len(data) < 4 || string(data[:4]) != "\x89PNG" {
		t.Errorf("Output file does not appear to be a valid PNG")
	}
}

// RT-1.10: FAL API error exits non-zero with error on stderr.
// User action: FAL API returns an error (e.g. server error).
// User observes: error message on terminal, no file created.
func TestCLI_api_error_exits_nonzero_RT1_10(t *testing.T) {
	bin := buildBinary(t)
	linkPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		http.Error(w, `{"detail": "model not found"}`, http.StatusBadRequest)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, linkPath, []string{"gen-img", outFile}, "a red cat", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit code, got 0")
	}
	if stderr == "" {
		t.Errorf("Expected error message on stderr, got nothing")
	}
	// Output file should not exist
	if _, err := os.Stat(outFile); err == nil {
		t.Errorf("Output file should not exist after API error")
	}
}

// RT-1.11: --help flag prints usage and exits zero.
// User action: runs "generate-image --help".
// User observes: usage information printed, clean exit.
func TestCLI_help_flag_prints_usage_RT1_11(t *testing.T) {
	bin := buildBinary(t)
	linkPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	// --help should work without stdin
	_, stderr, exitCode := runBinary(t, linkPath, []string{"--help"}, "", nil)

	if exitCode != 0 {
		t.Errorf("Expected exit code 0 for --help, got %d", exitCode)
	}
	lower := strings.ToLower(stderr)
	if !strings.Contains(lower, "usage") {
		t.Errorf("Expected usage text for --help, got: %q", stderr)
	}
}

// RT-1.12: --version flag prints version and exits zero.
// User action: runs "generate-image --version".
// User observes: version string printed, clean exit.
func TestCLI_version_flag_prints_version_RT1_12(t *testing.T) {
	bin := buildBinary(t)
	linkPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	stdout, _, exitCode := runBinary(t, linkPath, []string{"--version"}, "", nil)

	if exitCode != 0 {
		t.Errorf("Expected exit code 0 for --version, got %d", exitCode)
	}
	if !strings.Contains(stdout, "pix") {
		t.Errorf("Expected version output containing 'pix', got: %q", stdout)
	}
}

// RT-1.13: Cost printed to stderr when pricing data is available.
// User action: generates an image with a model that has pricing data.
// User observes: cost line like "Cost: $0.07 (per image)" on terminal.
func TestCLI_cost_printed_when_available_RT1_13(t *testing.T) {
	bin := buildBinary(t)
	linkPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	imageServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write(fakeImagePNG)
	}))
	t.Cleanup(imageServer.Close)

	pricingHandler := func(w http.ResponseWriter, r *http.Request) {
		resp := map[string]interface{}{
			"prices": []map[string]interface{}{
				{
					"unit_price": 0.07,
					"unit":       "image",
					"currency":   "USD",
				},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}

	server := startFakeAPI(t, successHandler(t, imageServer, nil), pricingHandler)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, _ := runBinary(t, linkPath, []string{"gen-img", outFile}, "a red cat", []string{"FAL_BASE_URL=" + server.URL})

	lower := strings.ToLower(stderr)
	if !strings.Contains(lower, "cost") {
		t.Errorf("Expected cost information on stderr, got: %q", stderr)
	}
	if !strings.Contains(stderr, "0.07") {
		t.Errorf("Expected cost amount on stderr, got: %q", stderr)
	}
}

// RT-1.14: No cost line on stderr when pricing data is unavailable.
// User action: generates an image with a model that has no pricing data.
// User observes: no cost line on terminal.
func TestCLI_no_cost_when_unavailable_RT1_14(t *testing.T) {
	bin := buildBinary(t)
	linkPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	imageServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write(fakeImagePNG)
	}))
	t.Cleanup(imageServer.Close)

	// Pricing endpoint returns empty prices
	pricingHandler := func(w http.ResponseWriter, r *http.Request) {
		resp := map[string]interface{}{
			"prices": []interface{}{},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}

	server := startFakeAPI(t, successHandler(t, imageServer, nil), pricingHandler)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, _ := runBinary(t, linkPath, []string{"gen-img", outFile}, "a red cat", []string{"FAL_BASE_URL=" + server.URL})

	if strings.Contains(stderr, "Cost:") {
		t.Errorf("Expected no cost line on stderr when pricing unavailable, got: %q", stderr)
	}
}

// RT-1.15: No extension given -- file written with API format extension.
// User action: runs "echo 'a cat' | generate-image sunset" (no extension).
// User observes: file written as sunset.jpg (or whatever format the API returns).
func TestCLI_no_extension_writes_api_format_RT1_15(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	imageServer := newImageServer(t, fakeImageJPEG, "image/jpeg")
	server := startFakeAPI(t, successHandler(t, imageServer, nil), nil)

	outDir := t.TempDir()
	outFile := filepath.Join(outDir, "sunset")
	_, _, exitCode := runBinary(t, binPath, []string{"gen-img", outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit code 0, got %d", exitCode)
	}

	// Should have written sunset.jpg
	expectedPath := filepath.Join(outDir, "sunset.jpg")
	if _, err := os.Stat(expectedPath); err != nil {
		// Check what files exist
		entries, _ := os.ReadDir(outDir)
		names := make([]string, 0, len(entries))
		for _, e := range entries {
			names = append(names, e.Name())
		}
		t.Fatalf("Expected %s to exist, found: %v", expectedPath, names)
	}
}

// RT-1.16: Matching extension given -- file written as-is.
// User action: runs "echo 'a cat' | generate-image sunset.jpg" and API returns JPEG.
// User observes: file written as sunset.jpg, no conversion needed.
func TestCLI_matching_extension_writes_as_is_RT1_16(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	imageServer := newImageServer(t, fakeImageJPEG, "image/jpeg")
	server := startFakeAPI(t, successHandler(t, imageServer, nil), nil)

	outDir := t.TempDir()
	outFile := filepath.Join(outDir, "sunset.jpg")
	_, _, exitCode := runBinary(t, binPath, []string{"gen-img", outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit code 0, got %d", exitCode)
	}

	info, err := os.Stat(outFile)
	if err != nil {
		t.Fatalf("Expected %s to exist: %v", outFile, err)
	}
	if info.Size() == 0 {
		t.Errorf("Output file is empty")
	}
}

// RT-1.17: Mismatched extension with magick available -- file converted.
// User action: runs "echo 'a cat' | generate-image sunset.jpg" and API returns PNG.
// User observes: file written as sunset.jpg (converted via magick).
func TestCLI_mismatched_extension_with_magick_converts_RT1_17(t *testing.T) {
	// Skip if magick is not available
	if _, err := exec.LookPath("magick"); err != nil {
		t.Skip("ImageMagick (magick) not available on PATH")
	}

	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	// API returns PNG, user requests .jpg -- conversion needed.
	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, successHandler(t, imageServer, nil), nil)

	outDir := t.TempDir()
	outFile := filepath.Join(outDir, "sunset.jpg")
	_, stderr, exitCode := runBinary(t, binPath, []string{"gen-img", outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Fatalf("Expected exit code 0, got %d; stderr: %s", exitCode, stderr)
	}

	data, err := os.ReadFile(outFile)
	if err != nil {
		t.Fatalf("Expected %s to exist: %v", outFile, err)
	}
	// Verify it's actually a JPEG (magic bytes), not PNG
	if len(data) < 2 || data[0] != 0xff || data[1] != 0xd8 {
		t.Errorf("Expected JPEG file after conversion, got different format (first bytes: %x)", data[:4])
	}
}

// RT-1.18: Mismatched extension without magick -- exits non-zero with clear error.
// User action: runs "echo 'a cat' | generate-image sunset.jpg" and API returns PNG,
// but magick is not on PATH.
// User observes: error message about format mismatch on terminal.
func TestCLI_mismatched_extension_without_magick_fails_RT1_18(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, successHandler(t, imageServer, nil), nil)

	outDir := t.TempDir()
	outFile := filepath.Join(outDir, "sunset.jpg")

	// Set PATH to empty so magick cannot be found
	_, stderr, exitCode := runBinary(t, binPath, []string{"gen-img", outFile}, "a cat", []string{
		"FAL_BASE_URL=" + server.URL,
		"PATH=",
	})

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit code when magick unavailable and format mismatched")
	}
	if stderr == "" {
		t.Errorf("Expected error message on stderr")
	}

	// The requested file should not exist (or should not be the wrong format)
	if _, err := os.Stat(outFile); err == nil {
		t.Errorf("Output file should not exist after conversion failure")
	}
}

// --- Key resolution chain tests ---

// setupEnvWithConfig is like setupEnv but takes full config YAML and
// optionally skips writing .env (to test key resolution from config).
func setupEnvWithConfig(t *testing.T, binary string, dotEnvContent string, configYAML string) string {
	t.Helper()
	tmpDir := t.TempDir()

	copyPath := filepath.Join(tmpDir, "pix")
	srcData, err := os.ReadFile(binary)
	if err != nil {
		t.Fatalf("Failed to read binary: %v", err)
	}
	if err := os.WriteFile(copyPath, srcData, 0755); err != nil {
		t.Fatalf("Failed to copy binary: %v", err)
	}

	// Write .env (may be empty to block fallback to ~/.config)
	if err := os.WriteFile(filepath.Join(tmpDir, ".env"), []byte(dotEnvContent), 0600); err != nil {
		t.Fatalf("Failed to write .env: %v", err)
	}

	if configYAML != "" {
		if err := os.WriteFile(filepath.Join(tmpDir, "config.yaml"), []byte(configYAML), 0644); err != nil {
			t.Fatalf("Failed to write config.yaml: %v", err)
		}
	}

	return copyPath
}

// RT-1.19: FAL_KEY env var takes priority over all other sources.
// User action: sets FAL_KEY in shell, config also has a command/file.
// User observes: the env var key is used, not the config one.
func TestCLI_env_var_takes_priority_RT1_19(t *testing.T) {
	bin := buildBinary(t)

	// Config points to a file with a different key
	tmpDir := t.TempDir()
	keyFile := filepath.Join(tmpDir, "fal.key")
	os.WriteFile(keyFile, []byte("file-key\n"), 0600)

	configYAML := fmt.Sprintf("model: fal-ai/grok-2-aurora\napi-keys:\n  fal:\n    file: %s\n", keyFile)
	binPath := setupEnvWithConfig(t, bin, "", configYAML)

	var capturedAuth string
	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		capturedAuth = r.Header.Get("Authorization")
		resp := map[string]interface{}{
			"images": []map[string]interface{}{
				{"url": imageServer.URL + "/image.png"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	runBinary(t, binPath, []string{"gen-img", outFile}, "a cat", []string{
		"FAL_BASE_URL=" + server.URL,
		"FAL_KEY=env-var-key",
	})

	if capturedAuth != "Key env-var-key" {
		t.Errorf("Expected env var key to take priority, got auth header: %q", capturedAuth)
	}
}

// RT-1.20: api-keys.fal.command in config.yaml provides the key.
// User action: config has a command that outputs the key.
// User observes: the command's output is used as the key.
func TestCLI_config_command_provides_key_RT1_20(t *testing.T) {
	bin := buildBinary(t)

	configYAML := "model: fal-ai/grok-2-aurora\napi-keys:\n  fal:\n    command: echo command-key\n"
	binPath := setupEnvWithConfig(t, bin, "", configYAML)

	var capturedAuth string
	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		capturedAuth = r.Header.Get("Authorization")
		resp := map[string]interface{}{
			"images": []map[string]interface{}{
				{"url": imageServer.URL + "/image.png"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	runBinary(t, binPath, []string{"gen-img", outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if capturedAuth != "Key command-key" {
		t.Errorf("Expected command key, got auth header: %q", capturedAuth)
	}
}

// RT-1.21: api-keys.fal.file in config.yaml provides the key.
// User action: config points to a key file.
// User observes: the key from that file is used.
func TestCLI_config_file_provides_key_RT1_21(t *testing.T) {
	bin := buildBinary(t)

	tmpDir := t.TempDir()
	keyFile := filepath.Join(tmpDir, "fal.key")
	os.WriteFile(keyFile, []byte("file-provided-key\n"), 0600)

	configYAML := fmt.Sprintf("model: fal-ai/grok-2-aurora\napi-keys:\n  fal:\n    file: %s\n", keyFile)
	binPath := setupEnvWithConfig(t, bin, "", configYAML)

	var capturedAuth string
	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		capturedAuth = r.Header.Get("Authorization")
		resp := map[string]interface{}{
			"images": []map[string]interface{}{
				{"url": imageServer.URL + "/image.png"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	runBinary(t, binPath, []string{"gen-img", outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if capturedAuth != "Key file-provided-key" {
		t.Errorf("Expected file key, got auth header: %q", capturedAuth)
	}
}

// RT-1.22: command takes priority over file when both specified.
// User action: config has both command and file for fal key.
// User observes: the command's output is used.
func TestCLI_command_beats_file_RT1_22(t *testing.T) {
	bin := buildBinary(t)

	tmpDir := t.TempDir()
	keyFile := filepath.Join(tmpDir, "fal.key")
	os.WriteFile(keyFile, []byte("file-key\n"), 0600)

	configYAML := fmt.Sprintf("model: fal-ai/grok-2-aurora\napi-keys:\n  fal:\n    command: echo command-wins\n    file: %s\n", keyFile)
	binPath := setupEnvWithConfig(t, bin, "", configYAML)

	var capturedAuth string
	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		capturedAuth = r.Header.Get("Authorization")
		resp := map[string]interface{}{
			"images": []map[string]interface{}{
				{"url": imageServer.URL + "/image.png"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	runBinary(t, binPath, []string{"gen-img", outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if capturedAuth != "Key command-wins" {
		t.Errorf("Expected command key to win over file, got auth header: %q", capturedAuth)
	}
}

// RT-1.23: .env fallback used when no config key sources defined.
// User action: config has no api-keys section, .env has the key.
// User observes: .env key is used (backward compatible).
func TestCLI_dotenv_fallback_RT1_23(t *testing.T) {
	bin := buildBinary(t)

	binPath := setupEnvWithConfig(t, bin, "FAL_KEY=dotenv-fallback-key\n", "model: fal-ai/grok-2-aurora\n")

	var capturedAuth string
	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		capturedAuth = r.Header.Get("Authorization")
		resp := map[string]interface{}{
			"images": []map[string]interface{}{
				{"url": imageServer.URL + "/image.png"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	runBinary(t, binPath, []string{"gen-img", outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if capturedAuth != "Key dotenv-fallback-key" {
		t.Errorf("Expected .env fallback key, got auth header: %q", capturedAuth)
	}
}

// --- --quiet, --dry-run, --preview tests ---

// RT-1.24: --quiet suppresses cost output on stderr.
// User action: runs with --quiet flag and a model that has pricing.
// User observes: no cost line on terminal.
func TestCLI_quiet_suppresses_cost_RT1_24(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	imageServer := newImageServer(t, fakeImagePNG, "image/png")

	pricingHandler := func(w http.ResponseWriter, r *http.Request) {
		resp := map[string]interface{}{
			"prices": []map[string]interface{}{
				{"unit_price": 0.07, "unit": "image", "currency": "USD"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}
	server := startFakeAPI(t, successHandler(t, imageServer, nil), pricingHandler)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, binPath, []string{"--quiet", "gen-img", outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit code 0, got %d", exitCode)
	}
	if strings.Contains(strings.ToLower(stderr), "cost") {
		t.Errorf("Expected no cost output with --quiet, got: %q", stderr)
	}
}

// RT-1.25: cost printed by default (without --quiet).
// User action: runs without --quiet flag and a model that has pricing.
// User observes: cost line on terminal.
func TestCLI_cost_printed_by_default_RT1_25(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	imageServer := newImageServer(t, fakeImagePNG, "image/png")

	pricingHandler := func(w http.ResponseWriter, r *http.Request) {
		resp := map[string]interface{}{
			"prices": []map[string]interface{}{
				{"unit_price": 0.07, "unit": "image", "currency": "USD"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}
	server := startFakeAPI(t, successHandler(t, imageServer, nil), pricingHandler)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, _ := runBinary(t, binPath, []string{"gen-img", outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if !strings.Contains(strings.ToLower(stderr), "cost") {
		t.Errorf("Expected cost output by default, got: %q", stderr)
	}
}

// RT-1.26: --dry-run prints config summary and exits zero without calling API.
// User action: runs with --dry-run flag.
// User observes: summary of what would happen (model, prompt, output), no API call.
func TestCLI_dry_run_prints_summary_RT1_26(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	apiCalled := false
	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		apiCalled = true
		http.Error(w, "should not be called", 500)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, binPath, []string{"gen-img", "--dry-run", outFile}, "a red cat", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit code 0 for --dry-run, got %d", exitCode)
	}
	if apiCalled {
		t.Errorf("API should not be called during --dry-run")
	}
	if !strings.Contains(stderr, "POST") {
		t.Errorf("Expected --dry-run to show POST request, got: %q", stderr)
	}
	if !strings.Contains(stderr, "grok-2-aurora") {
		t.Errorf("Expected --dry-run to show model in URL, got: %q", stderr)
	}
	if !strings.Contains(stderr, "a red cat") {
		t.Errorf("Expected --dry-run to show prompt in payload, got: %q", stderr)
	}
}

// RT-1.27: --dry-run does not create an output file.
// User action: runs with --dry-run flag.
// User observes: no output file created.
func TestCLI_dry_run_no_output_file_RT1_27(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	server := startFakeAPI(t, nil, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	runBinary(t, binPath, []string{"gen-img", "--dry-run", outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if _, err := os.Stat(outFile); err == nil {
		t.Errorf("Output file should not exist after --dry-run")
	}
}

// RT-1.28: --preview opens the image with the configured preview-command.
// User action: runs with --preview flag and preview-command set in config.
// User observes: image generated, then opened with the configured command.
func TestCLI_preview_opens_image_RT1_28(t *testing.T) {
	bin := buildBinary(t)

	// Use a preview command that writes a marker file to prove it ran.
	markerFile := filepath.Join(t.TempDir(), "preview-ran")
	previewCmd := fmt.Sprintf("touch %s", markerFile)
	configYAML := fmt.Sprintf("model: fal-ai/grok-2-aurora\npreview-command: \"%s\"\n", previewCmd)
	binPath := setupEnv(t, bin, "test-key", configYAML)

	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, successHandler(t, imageServer, nil), nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, _, exitCode := runBinary(t, binPath, []string{"gen-img", "--preview", outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit code 0, got %d", exitCode)
	}
	if _, err := os.Stat(markerFile); err != nil {
		t.Errorf("Preview command did not run (marker file missing)")
	}
}

// RT-1.29: --preview without preview-command uses platform default.
// User action: runs with --preview flag but no preview-command in config.
// User observes: image generated, platform default viewer invoked (which may
// fail in test env, but the binary should attempt it rather than error about config).
func TestCLI_preview_without_config_uses_default_RT1_29(t *testing.T) {
	bin := buildBinary(t)

	// Use a config with preview-command that writes a marker to prove default is overridden.
	// Then test WITHOUT preview-command -- the binary should not error about missing config.
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, successHandler(t, imageServer, nil), nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, binPath, []string{"gen-img", "--preview", outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	// The default preview command (open/xdg-open) may fail in a headless test env,
	// but the error should be about the preview command failing, NOT about
	// missing preview-command configuration.
	if exitCode != 0 {
		lower := strings.ToLower(stderr)
		if strings.Contains(lower, "requires preview-command") {
			t.Errorf("Should use platform default, not require config; got: %q", stderr)
		}
	}
}

// RT-1.30: --quiet and --dry-run together exits non-zero.
// User action: runs with both --quiet and --dry-run.
// User observes: error about conflicting flags.
func TestCLI_quiet_and_dry_run_conflict_RT1_30(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, binPath, []string{"--quiet", "gen-img", "--dry-run", "out.png"}, "a cat", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit code for --quiet + --dry-run")
	}
	if stderr == "" {
		t.Errorf("Expected error message about conflicting flags")
	}
}

// --- --cost tests ---

// startFakeAPIWithEstimate extends startFakeAPI with a separate handler for
// the /v1/models/pricing/estimate endpoint.
func startFakeAPIWithEstimate(t *testing.T, generateHandler http.HandlerFunc, pricingHandler http.HandlerFunc, estimateHandler http.HandlerFunc) *httptest.Server {
	t.Helper()
	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/v1/models/pricing/estimate" {
			if estimateHandler != nil {
				estimateHandler(w, r)
			} else {
				http.NotFound(w, r)
			}
			return
		}
		if strings.HasPrefix(r.URL.Path, "/v1/models/pricing") {
			if pricingHandler != nil {
				pricingHandler(w, r)
			} else {
				http.NotFound(w, r)
			}
			return
		}
		if generateHandler != nil {
			generateHandler(w, r)
		} else {
			http.NotFound(w, r)
		}
	})
	server := httptest.NewServer(mux)
	t.Cleanup(server.Close)
	return server
}

// fakePricingHandler returns a handler that serves a unit price response.
func fakePricingHandler(unitPrice float64, unit string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		resp := map[string]interface{}{
			"prices": []map[string]interface{}{
				{"endpoint_id": r.URL.Query().Get("endpoint_id"), "unit_price": unitPrice, "unit": unit, "currency": "USD"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}
}

// fakeEstimateHandler returns a handler that serves a cost estimate response.
func fakeEstimateHandler(totalCost float64) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		resp := map[string]interface{}{
			"estimate_type": "historical_api_price",
			"total_cost":    totalCost,
			"currency":      "USD",
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}
}

// RT-2.1: --cost prints unit price to stderr.
// User action: runs "generate-image --cost".
// User observes: unit price for the configured model on terminal.
func TestCLI_cost_flag_prints_unit_price_RT2_1(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	server := startFakeAPIWithEstimate(t, nil, fakePricingHandler(0.02, "images"), fakeEstimateHandler(0.02))

	_, stderr, exitCode := runBinary(t, binPath, []string{"cost"}, "", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit code 0, got %d; stderr: %s", exitCode, stderr)
	}
	if !strings.Contains(stderr, "0.02") {
		t.Errorf("Expected unit price in output, got: %q", stderr)
	}
	if !strings.Contains(stderr, "images") {
		t.Errorf("Expected unit type in output, got: %q", stderr)
	}
}

// RT-2.2: --cost exits zero without calling generation endpoint.
// User action: runs "generate-image --cost".
// User observes: pricing info, no image generated.
func TestCLI_cost_flag_no_generation_RT2_2(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	generationCalled := false
	server := startFakeAPIWithEstimate(t, func(w http.ResponseWriter, r *http.Request) {
		generationCalled = true
		http.Error(w, "should not be called", 500)
	}, fakePricingHandler(0.02, "images"), fakeEstimateHandler(0.02))

	_, _, exitCode := runBinary(t, binPath, []string{"cost"}, "", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit code 0, got %d", exitCode)
	}
	if generationCalled {
		t.Errorf("Generation endpoint should not be called with --cost")
	}
}

// RT-2.3: --cost does not require stdin input.
// User action: runs "generate-image --cost" with no piped input.
// User observes: pricing info without needing a prompt.
func TestCLI_cost_flag_no_stdin_required_RT2_3(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	server := startFakeAPIWithEstimate(t, nil, fakePricingHandler(0.02, "images"), fakeEstimateHandler(0.02))

	// Pass empty stdin explicitly
	_, stderr, exitCode := runBinary(t, binPath, []string{"cost"}, "", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit code 0 without stdin, got %d; stderr: %s", exitCode, stderr)
	}
}

// RT-2.4: --cost does not create an output file.
// User action: runs "generate-image --cost".
// User observes: no file created.
func TestCLI_cost_flag_no_output_file_RT2_4(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	server := startFakeAPIWithEstimate(t, nil, fakePricingHandler(0.02, "images"), fakeEstimateHandler(0.02))

	outDir := t.TempDir()
	_, _, _ = runBinary(t, binPath, []string{"cost"}, "", []string{"FAL_BASE_URL=" + server.URL})

	entries, _ := os.ReadDir(outDir)
	if len(entries) > 0 {
		t.Errorf("Expected no files created, found: %v", entries)
	}
}

// RT-2.5: Historical estimate printed when available.
// User action: runs "generate-image --cost" with a model that has usage history.
// User observes: both unit price and historical estimate on terminal.
func TestCLI_cost_flag_historical_estimate_RT2_5(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	server := startFakeAPIWithEstimate(t, nil, fakePricingHandler(0.02, "images"), fakeEstimateHandler(0.025))

	_, stderr, _ := runBinary(t, binPath, []string{"cost"}, "", []string{"FAL_BASE_URL=" + server.URL})

	if !strings.Contains(stderr, "0.025") {
		t.Errorf("Expected historical estimate in output, got: %q", stderr)
	}
}

// RT-2.6: "not available" message when no usage history exists.
// User action: runs "generate-image --cost" with a model that has no usage history.
// User observes: unit price shown, historical estimate says "not available".
func TestCLI_cost_flag_no_history_RT2_6(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	// Estimate endpoint returns 404 (no history)
	server := startFakeAPIWithEstimate(t, nil, fakePricingHandler(0.02, "images"), func(w http.ResponseWriter, r *http.Request) {
		http.NotFound(w, r)
	})

	_, stderr, _ := runBinary(t, binPath, []string{"cost"}, "", []string{"FAL_BASE_URL=" + server.URL})

	lower := strings.ToLower(stderr)
	if !strings.Contains(lower, "not available") {
		t.Errorf("Expected 'not available' for missing history, got: %q", stderr)
	}
}

// RT-2.7: --quiet suppresses --cost output.
// User action: runs "generate-image --quiet --cost".
// User observes: nothing on terminal.
func TestCLI_cost_flag_quiet_suppresses_RT2_7(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	server := startFakeAPIWithEstimate(t, nil, fakePricingHandler(0.02, "images"), fakeEstimateHandler(0.02))

	_, stderr, exitCode := runBinary(t, binPath, []string{"--quiet", "cost"}, "", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit code 0, got %d", exitCode)
	}
	if stderr != "" {
		t.Errorf("Expected no output with --quiet --cost, got: %q", stderr)
	}
}

// RT-2.8: --cost with --dry-run is not an error.
// User action: runs "generate-image --cost --dry-run".
// User observes: dry-run output (URLs that would be queried), no error.
func TestCLI_cost_flag_with_dry_run_RT2_8(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	server := startFakeAPIWithEstimate(t, nil, fakePricingHandler(0.02, "images"), fakeEstimateHandler(0.02))

	_, stderr, exitCode := runBinary(t, binPath, []string{"cost", "--dry-run"}, "", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit code 0, got %d; stderr: %s", exitCode, stderr)
	}
	if !strings.Contains(stderr, "dry run") {
		t.Errorf("Expected dry-run output, got: %q", stderr)
	}
}

// --- Subcommand dispatch tests (#5) ---

// RT-5.1: pix (no args) prints usage and exits zero.
// AC5.2 says no args should print usage and exit zero (help-first convention).
func TestPix_no_args_prints_usage_RT5_1(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, binPath, []string{}, "", nil)

	if exitCode != 0 {
		t.Errorf("Expected exit code 0 for no args, got %d", exitCode)
	}
	lower := strings.ToLower(stderr)
	if !strings.Contains(lower, "usage") {
		t.Errorf("Expected usage on stderr, got: %q", stderr)
	}
}

// RT-5.2: pix --help prints usage and exits zero.
func TestPix_help_flag_prints_usage_RT5_2(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, binPath, []string{"--help"}, "", nil)

	if exitCode != 0 {
		t.Errorf("Expected exit code 0 for --help, got %d", exitCode)
	}
	lower := strings.ToLower(stderr)
	if !strings.Contains(lower, "usage") {
		t.Errorf("Expected usage on stderr, got: %q", stderr)
	}
}

// RT-5.3: usage text lists all subcommands.
func TestPix_usage_lists_subcommands_RT5_3(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, _ := runBinary(t, binPath, []string{"--help"}, "", nil)

	if !strings.Contains(stderr, "gen-img") {
		t.Errorf("Expected 'gen-img' subcommand listed in usage, got: %q", stderr)
	}
	if !strings.Contains(stderr, "cost") {
		t.Errorf("Expected 'cost' subcommand listed in usage, got: %q", stderr)
	}
}

// RT-5.14: unknown subcommand exits non-zero with usage hint.
func TestPix_unknown_subcommand_RT5_14(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, binPath, []string{"nonsense"}, "", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit for unknown subcommand")
	}
	lower := strings.ToLower(stderr)
	if !strings.Contains(lower, "unknown") && !strings.Contains(lower, "usage") {
		t.Errorf("Expected usage hint or 'unknown' in error, got: %q", stderr)
	}
}

// RT-5.15: pix gen-img --help prints gen-img-specific usage line.
// Asserts on "Usage: pix generate-image" which the top-level usage does not contain.
func TestPix_genimg_help_RT5_15(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, binPath, []string{"gen-img", "--help"}, "", nil)

	if exitCode != 0 {
		t.Errorf("Expected exit code 0 for gen-img --help, got %d", exitCode)
	}
	if !strings.Contains(stderr, "Usage: pix generate-image") {
		t.Errorf("Expected gen-img-specific usage line 'Usage: pix generate-image', got: %q", stderr)
	}
}

// RT-5.16: pix cost --help prints cost-specific usage line.
// Asserts on "Usage: pix cost" which the top-level usage does not contain.
func TestPix_cost_help_RT5_16(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, binPath, []string{"cost", "--help"}, "", nil)

	if exitCode != 0 {
		t.Errorf("Expected exit code 0 for cost --help, got %d", exitCode)
	}
	if !strings.Contains(stderr, "Usage: pix cost") {
		t.Errorf("Expected cost-specific usage line 'Usage: pix cost', got: %q", stderr)
	}
}

// RT-5.17: pix gen-img -h (short form) prints gen-img-specific usage.
func TestPix_genimg_help_short_RT5_17(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, binPath, []string{"gen-img", "-h"}, "", nil)

	if exitCode != 0 {
		t.Errorf("Expected exit code 0 for gen-img -h, got %d", exitCode)
	}
	if !strings.Contains(stderr, "Usage: pix generate-image") {
		t.Errorf("Expected gen-img-specific usage, got: %q", stderr)
	}
}

// RT-5.18: pix cost --dry-run shows what would be queried without API call.
func TestPix_cost_dry_run_RT5_18(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	apiCalled := false
	server := startFakeAPIWithEstimate(t,
		func(w http.ResponseWriter, r *http.Request) {
			apiCalled = true
		},
		func(w http.ResponseWriter, r *http.Request) {
			apiCalled = true
		},
		func(w http.ResponseWriter, r *http.Request) {
			apiCalled = true
		},
	)

	_, stderr, exitCode := runBinary(t, binPath, []string{"cost", "--dry-run"}, "", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit code 0 for cost --dry-run, got %d", exitCode)
	}
	if apiCalled {
		t.Errorf("API should not be called during cost --dry-run")
	}
	// Expect the URLs that would be queried to be shown
	if !strings.Contains(stderr, "pricing") {
		t.Errorf("Expected dry-run output to mention pricing endpoint, got: %q", stderr)
	}
}

// RT-5.19: pix -h (top-level short form) prints usage and exits zero.
func TestPix_help_short_form_RT5_19(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, binPath, []string{"-h"}, "", nil)

	if exitCode != 0 {
		t.Errorf("Expected exit code 0 for -h, got %d", exitCode)
	}
	lower := strings.ToLower(stderr)
	if !strings.Contains(lower, "usage") {
		t.Errorf("Expected usage on stderr, got: %q", stderr)
	}
}

// RT-5.20: pix cost -h prints cost-specific usage.
func TestPix_cost_help_short_RT5_20(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, binPath, []string{"cost", "-h"}, "", nil)

	if exitCode != 0 {
		t.Errorf("Expected exit code 0 for cost -h, got %d", exitCode)
	}
	if !strings.Contains(stderr, "Usage: pix cost") {
		t.Errorf("Expected cost-specific usage, got: %q", stderr)
	}
}

// RT-5.21: --help is mutually exclusive with other args -- combining errors.
// User action: types "pix gen-img out.png --help" -- expects error and gen-img usage.
func TestPix_genimg_help_exclusive_RT5_21(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	apiCalled := false
	server := startFakeAPIWithEstimate(t,
		func(w http.ResponseWriter, r *http.Request) {
			apiCalled = true
		},
		nil, nil,
	)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, binPath, []string{"gen-img", outFile, "--help"}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit when --help combined with other args, got 0")
	}
	if apiCalled {
		t.Errorf("API should not be called when --help is present")
	}
	if !strings.Contains(stderr, "Usage: pix generate-image") {
		t.Errorf("Expected gen-img usage in error output, got: %q", stderr)
	}
	if _, err := os.Stat(outFile); err == nil {
		t.Errorf("Output file should not be created")
	}
}

// RT-5.22: pix --quiet gen-img out succeeds (correct global flag placement).
func TestPix_global_quiet_correct_position_RT5_22(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	imageServer := newImageServer(t, fakeImagePNG, "image/png")

	pricingHandler := func(w http.ResponseWriter, r *http.Request) {
		resp := map[string]interface{}{
			"prices": []map[string]interface{}{
				{"unit_price": 0.07, "unit": "image", "currency": "USD"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}
	server := startFakeAPI(t, successHandler(t, imageServer, nil), pricingHandler)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, binPath, []string{"--quiet", "gen-img", outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit code 0, got %d; stderr: %s", exitCode, stderr)
	}
	if strings.Contains(stderr, "Cost:") {
		t.Errorf("Expected no cost output with --quiet, got: %q", stderr)
	}
}

// RT-5.23: pix gen-img --quiet out errors (global flag in wrong position).
func TestPix_global_quiet_wrong_position_RT5_23(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, binPath, []string{"gen-img", "--quiet", outFile}, "a cat", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit for misplaced global flag")
	}
	if stderr == "" {
		t.Errorf("Expected error message about flag placement")
	}
}

// RT-5.24: pix --dry-run gen-img out errors (subcommand flag in global position).
func TestPix_subcommand_flag_wrong_position_RT5_24(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, binPath, []string{"--dry-run", "gen-img", outFile}, "a cat", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit for misplaced subcommand flag")
	}
	if stderr == "" {
		t.Errorf("Expected error message about flag placement")
	}
}

// RT-5.25: pix --help --quiet errors (--help mutual exclusion at top level).
func TestPix_help_with_other_flag_RT5_25(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, binPath, []string{"--help", "--quiet"}, "", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit when --help combined with other flag")
	}
	lower := strings.ToLower(stderr)
	if !strings.Contains(lower, "usage") {
		t.Errorf("Expected top-level usage in error output, got: %q", stderr)
	}
}

// RT-5.26: pix --help gen-img errors (--help mutual exclusion with subcommand).
func TestPix_help_with_subcommand_RT5_26(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, binPath, []string{"--help", "gen-img"}, "", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit when --help combined with subcommand")
	}
	lower := strings.ToLower(stderr)
	if !strings.Contains(lower, "usage") {
		t.Errorf("Expected top-level usage in error output, got: %q", stderr)
	}
}

// --- Reference image / image edit tests (#4) ---

// writeRefImage helper writes a fake image to disk with the given extension and content.
func writeRefImage(t *testing.T, dir, name string, content []byte) string {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, content, 0644); err != nil {
		t.Fatalf("Failed to write ref image %s: %v", path, err)
	}
	return path
}

// RT-4.1: Single reference image is base64-encoded and sent in image_urls.
func TestGenImg_single_ref_base64_RT4_1(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	refDir := t.TempDir()
	refPath := writeRefImage(t, refDir, "ref.png", fakeImagePNG)

	var capturedBody string
	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, successHandler(t, imageServer, &capturedBody), nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, binPath, []string{"gen-img", refPath, outFile}, "make blue", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Fatalf("Expected exit 0, got %d; stderr: %s", exitCode, stderr)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(capturedBody), &parsed); err != nil {
		t.Fatalf("Failed to parse request body: %v", err)
	}
	imageURLs, ok := parsed["image_urls"].([]interface{})
	if !ok || len(imageURLs) != 1 {
		t.Fatalf("Expected image_urls array with 1 entry, got: %v", parsed["image_urls"])
	}
	uri, _ := imageURLs[0].(string)
	if !strings.HasPrefix(uri, "data:image/png;base64,") {
		t.Errorf("Expected PNG data URI, got prefix: %q", uri[:min(40, len(uri))])
	}
}

// RT-4.2: Multiple reference images (up to 3) are all sent.
func TestGenImg_multiple_refs_RT4_2(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	refDir := t.TempDir()
	ref1 := writeRefImage(t, refDir, "ref1.png", fakeImagePNG)
	ref2 := writeRefImage(t, refDir, "ref2.png", fakeImagePNG)
	ref3 := writeRefImage(t, refDir, "ref3.png", fakeImagePNG)

	var capturedBody string
	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, successHandler(t, imageServer, &capturedBody), nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, binPath, []string{"gen-img", ref1, ref2, ref3, outFile}, "merge", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Fatalf("Expected exit 0, got %d; stderr: %s", exitCode, stderr)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(capturedBody), &parsed); err != nil {
		t.Fatalf("Failed to parse request body: %v", err)
	}
	imageURLs, ok := parsed["image_urls"].([]interface{})
	if !ok || len(imageURLs) != 3 {
		t.Fatalf("Expected image_urls with 3 entries, got %d", len(imageURLs))
	}
}

// RT-4.3: Edit endpoint (model path + /edit) is used when references are present.
func TestGenImg_edit_endpoint_with_refs_RT4_3(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	refDir := t.TempDir()
	refPath := writeRefImage(t, refDir, "ref.png", fakeImagePNG)

	var capturedPath string
	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		capturedPath = r.URL.Path
		resp := map[string]interface{}{
			"images": []map[string]interface{}{
				{"url": imageServer.URL + "/image.png"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	runBinary(t, binPath, []string{"gen-img", refPath, outFile}, "edit", []string{"FAL_BASE_URL=" + server.URL})

	if !strings.HasSuffix(capturedPath, "/edit") {
		t.Errorf("Expected request path to end with /edit, got: %q", capturedPath)
	}
}

// RT-4.4: Text-to-image endpoint is used when no references are present.
func TestGenImg_text_endpoint_without_refs_RT4_4(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	var capturedPath string
	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		capturedPath = r.URL.Path
		resp := map[string]interface{}{
			"images": []map[string]interface{}{
				{"url": imageServer.URL + "/image.png"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	runBinary(t, binPath, []string{"gen-img", outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if strings.HasSuffix(capturedPath, "/edit") {
		t.Errorf("Expected text-to-image endpoint without refs, got: %q", capturedPath)
	}
}

// RT-4.5: Last positional is always the target, regardless of refs.
func TestGenImg_last_positional_is_target_RT4_5(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	refDir := t.TempDir()
	ref1 := writeRefImage(t, refDir, "ref1.png", fakeImagePNG)
	ref2 := writeRefImage(t, refDir, "ref2.png", fakeImagePNG)

	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, successHandler(t, imageServer, nil), nil)

	outDir := t.TempDir()
	target := filepath.Join(outDir, "result.png")
	runBinary(t, binPath, []string{"gen-img", ref1, ref2, target}, "merge", []string{"FAL_BASE_URL=" + server.URL})

	if _, err := os.Stat(target); err != nil {
		t.Errorf("Expected target file %s to exist: %v", target, err)
	}
}

// RT-4.6: Nonexistent reference exits non-zero with clear error.
func TestGenImg_nonexistent_ref_RT4_6(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	apiCalled := false
	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		apiCalled = true
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, binPath, []string{"gen-img", "/nonexistent/ref.png", outFile}, "edit", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit for nonexistent ref")
	}
	if apiCalled {
		t.Errorf("API should not be called when ref validation fails")
	}
	if stderr == "" {
		t.Errorf("Expected error message")
	}
}

// RT-4.7: Non-image extension exits non-zero.
func TestGenImg_non_image_ref_extension_RT4_7(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	refDir := t.TempDir()
	textPath := writeRefImage(t, refDir, "notes.txt", []byte("not an image"))

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, binPath, []string{"gen-img", textPath, outFile}, "edit", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit for non-image extension")
	}
	if stderr == "" {
		t.Errorf("Expected error message")
	}
}

// RT-4.8: Four references exits non-zero.
func TestGenImg_too_many_refs_RT4_8(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	refDir := t.TempDir()
	r1 := writeRefImage(t, refDir, "r1.png", fakeImagePNG)
	r2 := writeRefImage(t, refDir, "r2.png", fakeImagePNG)
	r3 := writeRefImage(t, refDir, "r3.png", fakeImagePNG)
	r4 := writeRefImage(t, refDir, "r4.png", fakeImagePNG)

	apiCalled := false
	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		apiCalled = true
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, binPath, []string{"gen-img", r1, r2, r3, r4, outFile}, "edit", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit for >3 refs")
	}
	if apiCalled {
		t.Errorf("API should not be called when too many refs")
	}
	if stderr == "" {
		t.Errorf("Expected error message")
	}
}

// RT-4.9: Warning printed for each reference image.
func TestGenImg_ref_warning_RT4_9(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	refDir := t.TempDir()
	ref1 := writeRefImage(t, refDir, "ref1.png", fakeImagePNG)
	ref2 := writeRefImage(t, refDir, "ref2.png", fakeImagePNG)

	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, successHandler(t, imageServer, nil), nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, _ := runBinary(t, binPath, []string{"gen-img", ref1, ref2, outFile}, "merge", []string{"FAL_BASE_URL=" + server.URL})

	if !strings.Contains(stderr, "ref1.png") {
		t.Errorf("Expected warning mentioning ref1.png, got: %q", stderr)
	}
	if !strings.Contains(stderr, "ref2.png") {
		t.Errorf("Expected warning mentioning ref2.png, got: %q", stderr)
	}
}

// RT-4.10: --quiet suppresses warning.
func TestGenImg_quiet_suppresses_warning_RT4_10(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	refDir := t.TempDir()
	refPath := writeRefImage(t, refDir, "myref.png", fakeImagePNG)

	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, successHandler(t, imageServer, nil), nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, _ := runBinary(t, binPath, []string{"--quiet", "gen-img", refPath, outFile}, "edit", []string{"FAL_BASE_URL=" + server.URL})

	if strings.Contains(stderr, "myref.png") {
		t.Errorf("Expected no ref warning with --quiet, got: %q", stderr)
	}
}

// RT-4.11: Piped stdin reads all input (regression check on existing behaviour).
func TestGenImg_piped_stdin_reads_all_RT4_11(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	var capturedBody string
	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, successHandler(t, imageServer, &capturedBody), nil)

	multilinePrompt := "first line\nsecond line\nthird line"
	outFile := filepath.Join(t.TempDir(), "out.png")
	runBinary(t, binPath, []string{"gen-img", outFile}, multilinePrompt, []string{"FAL_BASE_URL=" + server.URL})

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(capturedBody), &parsed); err != nil {
		t.Fatalf("Failed to parse body: %v", err)
	}
	prompt, _ := parsed["prompt"].(string)
	if !strings.Contains(prompt, "second line") {
		t.Errorf("Expected full multi-line prompt, got: %q", prompt)
	}
}

// RT-4.12: --dry-run with refs shows edit endpoint URL.
func TestGenImg_dry_run_refs_shows_edit_endpoint_RT4_12(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	refDir := t.TempDir()
	refPath := writeRefImage(t, refDir, "ref.png", fakeImagePNG)

	apiCalled := false
	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		apiCalled = true
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, binPath, []string{"gen-img", "--dry-run", refPath, outFile}, "edit", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit 0, got %d; stderr: %s", exitCode, stderr)
	}
	if apiCalled {
		t.Errorf("API should not be called during --dry-run")
	}
	if !strings.Contains(stderr, "/edit") {
		t.Errorf("Expected /edit endpoint in dry-run output, got: %q", stderr)
	}
}

// RT-4.13: --dry-run with refs lists reference filenames.
func TestGenImg_dry_run_refs_lists_filenames_RT4_13(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	refDir := t.TempDir()
	refPath := writeRefImage(t, refDir, "myunique-ref.png", fakeImagePNG)

	server := startFakeAPI(t, nil, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, _ := runBinary(t, binPath, []string{"gen-img", "--dry-run", refPath, outFile}, "edit", []string{"FAL_BASE_URL=" + server.URL})

	if !strings.Contains(stderr, "myunique-ref.png") {
		t.Errorf("Expected ref filename in dry-run output, got: %q", stderr)
	}
}

// RT-4.14: --dry-run does not include base64 image data in output.
func TestGenImg_dry_run_no_base64_RT4_14(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	refDir := t.TempDir()
	refPath := writeRefImage(t, refDir, "ref.png", fakeImagePNG)

	server := startFakeAPI(t, nil, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, _ := runBinary(t, binPath, []string{"gen-img", "--dry-run", refPath, outFile}, "edit", []string{"FAL_BASE_URL=" + server.URL})

	if strings.Contains(stderr, "data:image/png;base64,") {
		t.Errorf("Dry-run should not include base64 data, got: %q", stderr)
	}
}

// RT-4.15: 'generate-image' (full name) is an alias for 'gen-img'.
func TestGenImg_full_name_alias_RT4_15(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, successHandler(t, imageServer, nil), nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, binPath, []string{"generate-image", outFile}, "a cat", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit 0 for 'generate-image' alias, got %d; stderr: %s", exitCode, stderr)
	}
	if _, err := os.Stat(outFile); err != nil {
		t.Errorf("Expected output file from 'generate-image' alias, got: %v", err)
	}
}

// RT-7.1: edit-image with one reference image dispatches and succeeds.
// User action: runs "echo 'make blue' | pix edit-image photo.png out.png".
// User observes: image written, no error.
func TestEditImg_one_ref_succeeds_RT7_1(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	refDir := t.TempDir()
	refPath := writeRefImage(t, refDir, "ref.png", fakeImagePNG)

	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, successHandler(t, imageServer, nil), nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, binPath, []string{"edit-image", refPath, outFile}, "make blue", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Errorf("Expected exit 0 for edit-image with one ref, got %d; stderr: %s", exitCode, stderr)
	}
	if _, err := os.Stat(outFile); err != nil {
		t.Errorf("Expected output file from edit-image, got: %v", err)
	}
}

// RT-7.2: edit-image with no positional arguments exits non-zero with usage.
// User action: types "pix edit-image" with no args.
// User observes: usage text on stderr, non-zero exit.
func TestEditImg_no_positionals_exits_nonzero_RT7_2(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, binPath, []string{"edit-image"}, "", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit code for edit-image with no args, got 0")
	}
	if !strings.Contains(strings.ToLower(stderr), "usage") {
		t.Errorf("Expected usage on stderr, got: %q", stderr)
	}
}

// RT-7.3: edit-image with only an output positional (no refs) exits non-zero
// with an error explaining a reference image is required.
// User action: runs "echo 'edit' | pix edit-image out.png" without supplying a reference.
// User observes: error stating a reference image is required, non-zero exit.
func TestEditImg_no_refs_exits_nonzero_RT7_3(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, binPath, []string{"edit-image", "out.png"}, "edit", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit code for edit-image without refs, got 0; stderr: %s", stderr)
	}
	lower := strings.ToLower(stderr)
	if !strings.Contains(lower, "reference image") {
		t.Errorf("Expected error mentioning reference image requirement, got: %q", stderr)
	}
}

// RT-7.4: edit-image with one ref calls FAL's /edit endpoint.
// User action: runs "echo 'edit' | pix edit-image photo.png out.png".
// User observes: image written; under the hood the /edit endpoint is invoked.
func TestEditImg_calls_edit_endpoint_RT7_4(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	refDir := t.TempDir()
	refPath := writeRefImage(t, refDir, "ref.png", fakeImagePNG)

	var capturedPath string
	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, func(w http.ResponseWriter, r *http.Request) {
		capturedPath = r.URL.Path
		resp := map[string]interface{}{
			"images": []map[string]interface{}{
				{"url": imageServer.URL + "/image.png"},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}, nil)

	outFile := filepath.Join(t.TempDir(), "out.png")
	runBinary(t, binPath, []string{"edit-image", refPath, outFile}, "edit", []string{"FAL_BASE_URL=" + server.URL})

	if !strings.HasSuffix(capturedPath, "/edit") {
		t.Errorf("Expected request path to end with /edit, got: %q", capturedPath)
	}
}

// RT-7.5: edit-image with three reference images sends three image_urls.
// User action: runs "pix edit-image a.png b.png c.png merged.png".
// User observes: image written; payload contains three image_urls entries.
func TestEditImg_three_refs_RT7_5(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	refDir := t.TempDir()
	r1 := writeRefImage(t, refDir, "a.png", fakeImagePNG)
	r2 := writeRefImage(t, refDir, "b.png", fakeImagePNG)
	r3 := writeRefImage(t, refDir, "c.png", fakeImagePNG)

	var capturedBody string
	imageServer := newImageServer(t, fakeImagePNG, "image/png")
	server := startFakeAPI(t, successHandler(t, imageServer, &capturedBody), nil)

	outFile := filepath.Join(t.TempDir(), "merged.png")
	_, stderr, exitCode := runBinary(t, binPath, []string{"edit-image", r1, r2, r3, outFile}, "merge", []string{"FAL_BASE_URL=" + server.URL})

	if exitCode != 0 {
		t.Fatalf("Expected exit 0, got %d; stderr: %s", exitCode, stderr)
	}
	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(capturedBody), &parsed); err != nil {
		t.Fatalf("Failed to parse request body: %v", err)
	}
	urls, ok := parsed["image_urls"].([]interface{})
	if !ok || len(urls) != 3 {
		t.Fatalf("Expected 3 image_urls, got: %v", parsed["image_urls"])
	}
}

// RT-7.6: edit-image with more than the maximum (3) reference images exits non-zero.
// User action: runs "pix edit-image a.png b.png c.png d.png out.png".
// User observes: error stating max ref images exceeded, non-zero exit.
func TestEditImg_too_many_refs_RT7_6(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	refDir := t.TempDir()
	r1 := writeRefImage(t, refDir, "a.png", fakeImagePNG)
	r2 := writeRefImage(t, refDir, "b.png", fakeImagePNG)
	r3 := writeRefImage(t, refDir, "c.png", fakeImagePNG)
	r4 := writeRefImage(t, refDir, "d.png", fakeImagePNG)

	outFile := filepath.Join(t.TempDir(), "out.png")
	_, stderr, exitCode := runBinary(t, binPath, []string{"edit-image", r1, r2, r3, r4, outFile}, "edit", nil)

	if exitCode == 0 {
		t.Errorf("Expected non-zero exit for too many refs, got 0; stderr: %s", stderr)
	}
	lower := strings.ToLower(stderr)
	if !strings.Contains(lower, "maximum") && !strings.Contains(lower, "too many") {
		t.Errorf("Expected error about exceeding max reference images, got: %q", stderr)
	}
}

// RT-7.7: edit-image --help prints usage that mentions reference image as required.
// User action: runs "pix edit-image --help".
// User observes: usage text noting that a reference image is required.
func TestEditImg_help_text_mentions_required_ref_RT7_7(t *testing.T) {
	bin := buildBinary(t)
	binPath := setupEnv(t, bin, "test-key", "model: fal-ai/grok-2-aurora\n")

	_, stderr, exitCode := runBinary(t, binPath, []string{"edit-image", "--help"}, "", nil)

	if exitCode != 0 {
		t.Errorf("Expected exit 0 for --help, got %d", exitCode)
	}
	lower := strings.ToLower(stderr)
	if !strings.Contains(lower, "reference image") {
		t.Errorf("Expected --help to mention reference image, got: %q", stderr)
	}
	if !strings.Contains(lower, "required") {
		t.Errorf("Expected --help to mention reference image is required, got: %q", stderr)
	}
}
